//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Array
    {
        public string ArrayId { get; set; }
        public string ArrayName { get; set; }
        public string ShortArrayName { get; set; }
        public Nullable<bool> IsSubArray { get; set; }
        public string MasterArrayId { get; set; }
        public string LIMArrayNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    }
}
