//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditId { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDt { get; set; }
        public string Type { get; set; }
        public string RecordId { get; set; }
        public string Description { get; set; }
    }
}
