//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public string BatchName { get; set; }
        public System.DateTime RunDate { get; set; }
        public int BlockNumber { get; set; }
        public string LotNumber { get; set; }
        public string AntigenGroup { get; set; }
        public string CCType { get; set; }
        public string AntigenId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    }
}
