//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibControl
    {
        public string CCId { get; set; }
        public string LotNumber { get; set; }
        public string ArrayId { get; set; }
        public string AntigenId { get; set; }
        public string AntigenGroup { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
        public Nullable<System.DateTime> DilutionDate { get; set; }
        public string DilutionFactor { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Serum { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    }
}
