//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    
    public partial class AntigensAssingedToArray
    {
        public string AntigenId { get; set; }
        public string AntigenName { get; set; }
        public string ArrayId { get; set; }
        public string ArrayName { get; set; }
        public string MasterArrayId { get; set; }
        public string MasterArrayName { get; set; }
        public bool IsSubArray { get; set; }
        public string Group { get; set; }
    }
}
