//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<bool> IsFirstLogin { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
